version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - path: ./client/.env
  server:
    build: ./server
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
